export { default as CalculationDetails } from 'assets/images/screenshots/investCalc/ipad/light/calculation-details.webp'
export { default as CalculationYearDetail } from 'assets/images/screenshots/investCalc/ipad/light/calculation-year-detail.webp'
export { default as CalculationYearlyGoals } from 'assets/images/screenshots/investCalc/ipad/light/calculation-yearly-goals.webp'
export { default as Calculations } from 'assets/images/screenshots/investCalc/ipad/light/calculations.webp'
export { default as CreateCalculation } from 'assets/images/screenshots/investCalc/ipad/light/create-calculation.webp'
export { default as EditCalculationYear } from 'assets/images/screenshots/investCalc/ipad/light/edit-calculation-year.webp'
