export { default as DualImage } from 'assets/images/screenshots/bloom/ipad/light/dual-image.webp'
export { default as SingleImageCouple } from 'assets/images/screenshots/bloom/ipad/light/single-image-couple.webp'
export { default as SingleImageEngaged } from 'assets/images/screenshots/bloom/ipad/light/single-image-engaged.webp'
export { default as SingleImageMarried } from 'assets/images/screenshots/bloom/ipad/light/single-image-married.webp'
export { default as Widgets } from 'assets/images/screenshots/bloom/ipad/light/widgets.webp'
