export { default as CalculationDetails } from 'assets/images/screenshots/investCalc/iphone/dark/calculation-details.webp'
export { default as CalculationYearDetail } from 'assets/images/screenshots/investCalc/iphone/dark/calculation-year-detail.webp'
export { default as CalculationYearlyGoals } from 'assets/images/screenshots/investCalc/iphone/dark/calculation-yearly-goals.webp'
export { default as Calculations } from 'assets/images/screenshots/investCalc/iphone/dark/calculations.webp'
export { default as CreateCalculation } from 'assets/images/screenshots/investCalc/iphone/dark/create-calculation.webp'
export { default as EditCalculationYear } from 'assets/images/screenshots/investCalc/iphone/dark/edit-calculation-year.webp'
