export * as ScreenshotsIpadDark from './ipad/dark'
export * as ScreenshotsIpadLight from './ipad/light'
export * as ScreenshotsIphoneDark from './iphone/dark'
export * as ScreenshotsIphoneLight from './iphone/light'
export * as ScreenshotsMacDark from './mac/dark'
export * as ScreenshotsMacLight from './mac/light'
