export { default as Calculations } from './calculations.webp'
export { default as CreateCalculation } from './create-calculation.webp'
export { default as CalculationDetails } from './calculation-details.webp'
export { default as CalculationYearlyGoals } from './calculation-yearly-goals.webp'
export { default as CalculationYearDetail } from './calculation-year-detail.webp'
export { default as EditCalculationYear } from './edit-calculation-year.webp'
